export interface Article {
  id: string;
  title: string;
  slug: string;
  category: string;
  categorySlug: string;
  date: string;
  image: string;
  excerpt: string;
  readTime: string;
}

export const heroArticles: Article[] = [
  {
    id: "1",
    title: "The Hidden Cost of Staying: Why High Achievers Can't Leave Jobs That Are Killing Them",
    slug: "hidden-cost-of-staying",
    category: "Burnout",
    categorySlug: "burnout",
    date: "18 Apr 2026",
    image: "https://picsum.photos/seed/office1/800/533",
    excerpt: "New research from the EU Workplace Mental Health Index reveals a counterintuitive pattern: the more successful the professional, the longer they stay in a role causing measurable psychological harm.",
    readTime: "8 min",
  },
  {
    id: "2",
    title: "AIRD: The New Clinical Framework for AI-Driven Career Anxiety",
    slug: "aird-clinical-framework",
    category: "AI Disruption",
    categorySlug: "ai-disruption",
    date: "17 Apr 2026",
    image: "https://picsum.photos/seed/tech2/800/533",
    excerpt: "Psychologists at UCL have proposed a formal diagnostic criterion for the anticipatory grief experienced by professionals facing AI displacement.",
    readTime: "6 min",
  },
  {
    id: "3",
    title: "Why Companies Are Now Paying a Premium for Human Judgment",
    slug: "premium-human-judgment",
    category: "Opportunity",
    categorySlug: "opportunity",
    date: "16 Apr 2026",
    image: "https://picsum.photos/seed/meeting3/800/533",
    excerpt: "McKinsey's Q1 2026 workforce data shows senior professionals with 15+ years of domain experience commanding 34% higher wages than their AI-augmented equivalents from 2022.",
    readTime: "5 min",
  },
  {
    id: "4",
    title: "Male Isolation at Midlife: The Silent Crisis No One Is Funding",
    slug: "male-isolation-midlife",
    category: "Mental Health",
    categorySlug: "mental-health",
    date: "15 Apr 2026",
    image: "https://picsum.photos/seed/solitude4/800/533",
    excerpt: "While women's midlife mental health receives growing policy attention, men aged 45–60 are experiencing the steepest rise in social isolation since records began.",
    readTime: "9 min",
  },
  {
    id: "5",
    title: "The Encore Career Boom: 50+ Professionals Outearning Their Former Selves",
    slug: "encore-career-boom",
    category: "Reinvention",
    categorySlug: "reinvention",
    date: "14 Apr 2026",
    image: "https://picsum.photos/seed/success5/800/533",
    excerpt: "A new cohort study tracking 2,400 professionals who left corporate roles after 45 shows that within three years, 61% had surpassed their previous income.",
    readTime: "7 min",
  },
  {
    id: "6",
    title: "UAE 2026 Mental Health at Work Law: What It Means for Expat Professionals",
    slug: "uae-mental-health-law-2026",
    category: "Policy",
    categorySlug: "policy",
    date: "13 Apr 2026",
    image: "https://picsum.photos/seed/dubai6/800/533",
    excerpt: "The UAE's landmark workplace mental health legislation takes effect in Q3 2026. Here is what changes — and what remains unaddressed.",
    readTime: "6 min",
  },
];

export const featuredArticles: Article[] = [
  {
    id: "7",
    title: "Portfolio Careers at 50: The Framework That Replaced the Job Title",
    slug: "portfolio-careers-50",
    category: "Reinvention",
    categorySlug: "reinvention",
    date: "17 Apr 2026",
    image: "https://picsum.photos/seed/portfolio7/1200/800",
    excerpt: "For a growing cohort of senior professionals, the question is no longer 'what do you do?' but 'which of your things are you doing today?'",
    readTime: "11 min",
  },
  {
    id: "8",
    title: "The Identity Collapse Nobody Warns You About When You Leave Corporate Life",
    slug: "identity-collapse-leaving-corporate",
    category: "Mental Health",
    categorySlug: "mental-health",
    date: "16 Apr 2026",
    image: "https://picsum.photos/seed/identity8/1200/800",
    excerpt: "Therapists are seeing a surge in clients experiencing what one researcher calls 'the vacuum after the title' — a disorientation that job-change advice never prepares you for.",
    readTime: "10 min",
  },
];

export const burnoutArticles: Article[] = [
  {
    id: "9",
    title: "Burnout Rates Among 45–55-Year-Olds Hit Record High in EU Survey",
    slug: "burnout-rates-eu-survey-2026",
    category: "Burnout",
    categorySlug: "burnout",
    date: "16 Apr 2026",
    image: "https://picsum.photos/seed/burnout9/600/400",
    excerpt: "",
    readTime: "5 min",
  },
  {
    id: "10",
    title: "Anticipatory Job Anxiety: The Pre-Displacement Stress Epidemic",
    slug: "anticipatory-job-anxiety",
    category: "AI Disruption",
    categorySlug: "ai-disruption",
    date: "15 Apr 2026",
    image: "https://picsum.photos/seed/anxiety10/600/400",
    excerpt: "",
    readTime: "7 min",
  },
  {
    id: "11",
    title: "Menopause and Career: The Workplace Conversation That's Finally Happening",
    slug: "menopause-career-workplace",
    category: "Mental Health",
    categorySlug: "mental-health",
    date: "14 Apr 2026",
    image: "https://picsum.photos/seed/women11/600/400",
    excerpt: "",
    readTime: "6 min",
  },
  {
    id: "12",
    title: "EU Psychosocial Risk Legislation: What Employers Must Do by September",
    slug: "eu-psychosocial-risk-legislation",
    category: "Policy",
    categorySlug: "policy",
    date: "12 Apr 2026",
    image: "https://picsum.photos/seed/policy12/600/400",
    excerpt: "",
    readTime: "4 min",
  },
];

export const reinventionArticles: Article[] = [
  {
    id: "13",
    title: "Second-Act Founders: The Data Behind Midlife Entrepreneurship",
    slug: "second-act-founders-data",
    category: "Reinvention",
    categorySlug: "reinvention",
    date: "15 Apr 2026",
    image: "https://picsum.photos/seed/founder13/600/400",
    excerpt: "",
    readTime: "8 min",
  },
  {
    id: "14",
    title: "The Happiness U-Curve: New Research on Why Life Gets Better After 50",
    slug: "happiness-u-curve-after-50",
    category: "Research",
    categorySlug: "research",
    date: "14 Apr 2026",
    image: "https://picsum.photos/seed/happy14/600/400",
    excerpt: "",
    readTime: "5 min",
  },
  {
    id: "15",
    title: "How One Former McKinsey Partner Built a Meaning-Led Practice at 54",
    slug: "mckinsey-partner-reinvention",
    category: "Case Study",
    categorySlug: "case-study",
    date: "13 Apr 2026",
    image: "https://picsum.photos/seed/consult15/600/400",
    excerpt: "",
    readTime: "12 min",
  },
  {
    id: "16",
    title: "Wisdom Economy: Why Experienced Professionals Are the New Premium Asset",
    slug: "wisdom-economy-experienced-professionals",
    category: "Opportunity",
    categorySlug: "opportunity",
    date: "11 Apr 2026",
    image: "https://picsum.photos/seed/wisdom16/600/400",
    excerpt: "",
    readTime: "6 min",
  },
];

export const researchArticles: Article[] = [
  {
    id: "17",
    title: "Stanford Research: Midlife Cognitive Advantages That AI Cannot Replicate",
    slug: "stanford-midlife-cognitive-advantages",
    category: "Research",
    categorySlug: "research",
    date: "14 Apr 2026",
    image: "https://picsum.photos/seed/research17/600/400",
    excerpt: "",
    readTime: "7 min",
  },
  {
    id: "18",
    title: "The 15 Patterns: A New Framework for Mapping Professional Crisis",
    slug: "15-patterns-professional-crisis",
    category: "Research",
    categorySlug: "research",
    date: "12 Apr 2026",
    image: "https://picsum.photos/seed/patterns18/600/400",
    excerpt: "",
    readTime: "9 min",
  },
  {
    id: "19",
    title: "Identity Coherence and Career Satisfaction: What the Longitudinal Data Shows",
    slug: "identity-coherence-career-satisfaction",
    category: "Research",
    categorySlug: "research",
    date: "10 Apr 2026",
    image: "https://picsum.photos/seed/data19/600/400",
    excerpt: "",
    readTime: "6 min",
  },
  {
    id: "20",
    title: "Skill-Market Mismatch at 50: The Gap Nobody Trains You to Bridge",
    slug: "skill-market-mismatch-50",
    category: "AI Disruption",
    categorySlug: "ai-disruption",
    date: "8 Apr 2026",
    image: "https://picsum.photos/seed/skills20/600/400",
    excerpt: "",
    readTime: "5 min",
  },
];

export const mostRead: Article[] = [
  heroArticles[0],
  heroArticles[3],
  reinventionArticles[0],
  researchArticles[1],
  burnoutArticles[0],
];
